- name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-pip \
              build-essential \
              git \
              python3-dev \
              ffmpeg \
              libltdl-dev \
              libsdl2-dev \
              libsdl2-image-dev \
              libsdl2-mixer-dev \
              libsdl2-ttf-dev \
              libportmidi-dev \
              libswscale-dev \
              libavformat-dev \
              libavcodec-dev \
              zlib1g-dev \
              openjdk-17-jdk \
              unzip \
              zip \
              autoconf \
              libtool \
              pkg-config \
              libncurses5-dev \
              libncursesw5-dev \
              libtinfo5 \
              libffi-dev \
              libssl-dev \
              cmake
